# Easier pane navigation
bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-j select-pane -D
bind -n C-k select-pane -U


set -g mouse on

# Enable vi-style copy mode
setw -g mode-keys vi

# Enable mouse support
set -g mouse on

# Increase scrollback buffer
set -g history-limit 10000



# Enable vi keys in copy mode
setw -g mode-keys vi

# Bind v to start selection (like Vim visual mode)
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Bind y to copy selection to system clipboard with wl-copy
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# Optional: make V select whole lines
bind-key -T copy-mode-vi V send-keys -X select-line

# Start numbering from 1
set -g base-index 1
set -g pane-base-index 1
set -g allow-passthrough on

# Use Alt + number to switch between windows
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Directory action 
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g @plugin 'tmux-plugins/tmux-resurrect'

# --- Named session save/restore with fzf ---
bind Space run-shell "~/.tmux/tmux_multi_session.sh"

# initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
