# ~/.config/starship.toml
[line_break]
disabled = true
add_newline = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"

[cmd_duration]
min_time = 0  # Show command duration always
format = "[$duration]($style)"
show_milliseconds = true

[directory]
truncation_length = 5
style = "bold grey"
format = "[](bold 214)[$path]($style)[$lock_symbol]($lock_style) "

[git_status]
disabled = true

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "🍣 "
style = "bold yellow"

# [git_commit]
# commit_hash_length = 8
# style = "bold white"

[username]
style_user = "bold 100"
style_root = "bold grey"
show_always = true
format = "[ ](white)[$user]($style)"


#format = "[ ](white)[$user]($style)"

[hostname]
ssh_only = false
format = "[ $hostname]($style) "
trim_at = "-"
style = "bold purple"
disabled = true

[python]
format = "[$symbol$version]($style) "
style = "bold green"

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = true
